In [47]:
print("Задание 1")

Задание 1


In [80]:
import numpy as np

In [81]:
# первый способ
N = input()
x = np.arange(0,int(N))
np.flip(x,0)

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [82]:
# второй способ
L = input()
x = np.arange(0,int(L))
x[::-1]

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [83]:
print("Задание 2")

Задание 2


In [100]:
K = input()
a = np.diag(np.flip(np.arange(0,int(K)),0))
print(f'Сумма главной диагонали равна =',sum(np.diagonal(a)))

10
Сумма главной диагонали равна = 45


In [101]:
print("Задание 3")

Задание 3


In [106]:
# (4x + 2y + z = 4)
# (x + 3y = 12)
# (5y + 4z = -3)
# x = 0,466 y = 3,844 z = -5,55
# решал вручную

In [110]:
from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [111]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [133]:
print("Задание 4")

Задание 4


In [134]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [140]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [141]:
import matplotlib.pyplot as plt

In [155]:
# делал вручную для самопроверки
print(cosine( users_stats[0], next_user_stats ))
print(cosine( users_stats[1], next_user_stats ))
print(cosine( users_stats[2], next_user_stats ))
print(cosine( users_stats[3], next_user_stats ))
print(cosine( users_stats[4], next_user_stats ))
print(cosine( users_stats[5], next_user_stats ))
print(cosine( users_stats[6], next_user_stats ))
print(cosine( users_stats[7], next_user_stats ))
print(cosine( users_stats[8], next_user_stats ))
print(cosine( users_stats[9], next_user_stats ))

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0


In [174]:
cosine_check = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)
np.apply_along_axis(cosine, 1, users_stats, next_user_stats)

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

In [176]:
the_most_similar_user = np.argmax(cosine_check)
print(the_most_similar_user)

7
